### ISSUE TITLE
Swaggman dependency does not work.

### ISSUE THREAD

**Issue by ArtyomIvanov-dev** [ringcentral/engage-digital-api-docs#39]
Apparently, github.com/grokify/swaggman was renamed to github.com/grokify/spectrum

I tried to replace it, but the spectrum is not compatible with go@1.15.x

It raises the error: 
```
> go version #go version go1.15.15 darwin/amd64(OSX)
> go get github.com/grokify/spectrum
../../../../go/pkg/mod/github.com/grokify/simplego@v0.30.2/encoding/jsonutil/jsonutil.go:9:2: package io/fs is not in GOROOT (/usr/local/Cellar/go@1.15/1.15.15/libexec/src/io/fs)
```

Same in CI: https://github.com/ringcentral/engage-digital-api-docs/runs/3349668209?check_suite_focus=true

**Comment by nel** [comment]
@grokify it seems your latest update of github.com/grokify/swaggman broke our postman generation, it's probably trivial but we are not go developer. What version is supported by spectrum ? Maybe it's just a dependency missing or something.

**Comment by nel** [comment]
Ok I fixed it, we are now using spectrum
